# Site settings
title: "Ondrej Klejch: Senior Researcher at the University of Edinburgh"
description: "Ondrej Klejch: Senior Researcher at the University of Edinburgh"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ondrej Klejch"
resume_title:                   "Senior Researcher"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ondrej.klejch@gmail.com"

resume_header_intro: "
  <p>
    I am a Senior Researcher within the <a href='http://www.ilcc.inf.ed.ac.uk'>ILCC</a> and <a href='http://www.cstr.ed.ac.uk/'>CSTR</a> institutes of the School of Informatics at the University of Edinburgh.  I have been working on building speech-to-text systems with limited training data and supervision within several large projects funded by EPSRC, H2020, and IARPA. I am currently working with <a href='http://homepages.inf.ed.ac.uk/pbell1/'>Peter Bell</a> on zero-resource cross-lingual transfer for low-resource languages within the <a href='https://unmute.tech'>EPSRC UnMute</a> project.
  </p>"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ondrejklejch"
  resume_twitter_url:           "http://twitter.com/ondrejklejch"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ondrejklejch"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.ondrejklejch.cz"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
